### PR TITLE
Added a profile to each module for building the JDBC driver JARs with…

### PR DESCRIPTION
**Pull request by vhajdari**
… the socket factory dependencies.

In this PR you'll find the addition of a profile for building a fat JAR with the Socket Factory  dependency for each driver module.  All the drivers can be built with a single Maven command.

This modification is required to support Google Data Fusion (CDAP).  Data Fusion requires the Socket Factory dependency in the JDBC drivers in order to connect to Cloud SQL from Wrangler for ad-hoc DB access and Dataproc for executing pipelines.

For instruction on how this PR would be used with Data Fusion and CDAP refer to the following blog article: https://medium.com/cdapio/cloud-databases-cdap-a4f77f02ec95

### CODE REVIEW

**Comment by kurtisvg** [comment]
@vhajdari - This looks great - I'm happy to pull this in. It would also be great if you could include brief instructions for building as `jar-with-dependencies` in the README.md as well.

Also, please take a look at @googlebot's comment and sign the CLA. This is necessary before I can accept the PR.

**Comment by vhajdari** [comment]
@googlebot I signed it!

Regards,

Tony Hajdari

**Comment by kurtisvg** [comment]
@vhajdari Thanks!

**Comment by vhajdari** [comment]
Thanks for the merge.  I just updated the Readme.md to add the build
instructions.  A new PR is in.
Regards,

Tony Hajdari

**Pull request merged**
